package service

import "errors"

var (
	ErrInvalidLauncherVersion            = errors.New("invalid launcher version")
	ErrInvalidLauncherUser               = errors.New("invalid launcher user")
	ErrInvalidLauncherUserProductKey     = errors.New("invalid launcher user product key")
	ErrInvalidLauncherSessionAccessToken = errors.New("invalid launcher access token")
	ErrLauncherSessionAccessTokenExpired = errors.New("launcher access token expired")
	ErrInvalidAuthStateOrCode            = errors.New("invalid auth state or code")
	ErrInvaliClientID                    = errors.New("invalid client id")
	ErrOIDCSessionExpired                = errors.New("session access token expired")
	ErrNoGameManagementRoleUpdated       = errors.New("no game management role updated")
	ErrInvalidRole                       = errors.New("invalid role")
	ErrInvalidEditionID                  = errors.New("invalid edition id")
	ErrInvalidGameID                     = errors.New("invalid game id")
	ErrInvalidGameVersionID              = errors.New("invalid game version id")
	ErrInvalidGameImageID                = errors.New("invalid game image id")
	ErrInvalidGameVideoID                = errors.New("invalid game video id")
	ErrInvalidGameFileID                 = errors.New("invalid game file id")
	ErrInvalidUserID                     = errors.New("invalid user id")
	ErrInvalidGameFileType               = errors.New("invalid game file type")
	ErrInvalidKeyNum                     = errors.New("invalid key num")
	ErrInvalidProductKey                 = errors.New("invalid product key")
	ErrInvalidAccessToken                = errors.New("invalid access token")
	ErrInvalidSeatStatus                 = errors.New("invalid seat status")
	ErrKeyAlreadyActivated               = errors.New("key already activated")
	ErrKeyAlreadyRevoked                 = errors.New("key already revoked")
	ErrExpiredAccessToken                = errors.New("expired access token")
	ErrForbidden                         = errors.New("forbidden")
	ErrInvalidFormat                     = errors.New("invalid format")
	ErrNoGame                            = errors.New("no game")
	ErrNoGameImage                       = errors.New("no game image")
	ErrNoGameVideo                       = errors.New("no game video")
	ErrNoGameVersion                     = errors.New("no game version")
	ErrNoGameFile                        = errors.New("no game file")
	ErrNoGameURL                         = errors.New("no game url")
	ErrNoSeat                            = errors.New("no seat")
	ErrNoLauncherVersion                 = errors.New("no launcher version")
	ErrGameFileAlreadyExists             = errors.New("game file already exists")
	ErrGameURLAlreadyExists              = errors.New("game url already exists")
	ErrDuplicateGame                     = errors.New("duplicate game")
	ErrDuplicateGameVersion              = errors.New("duplicate game version")
	ErrInvalidLimit                      = errors.New("invalid limit")
	ErrNoAsset                           = errors.New("no asset")
	ErrNoGameGenre                       = errors.New("no game genre")
	ErrNoGameGenreUpdated                = errors.New("no game genre updated")
	ErrDuplicateGameGenre                = errors.New("duplicate game genre")
	ErrDuplicateGameGenreName            = errors.New("duplicate game genre name")
	ErrInvalidGamesSortType              = errors.New("invalid games sort type")
)
