package service

import "errors"

var (
	ErrInvalidLauncherVersion            = errors.New("invalid launcher version")
	ErrInvalidLauncherUser               = errors.New("invalid launcher user")
	ErrInvalidLauncherUserProductKey     = errors.New("invalid launcher user product key")
	ErrInvalidLauncherSessionAccessToken = errors.New("invalid launcher access token")
	ErrLauncherSessionAccessTokenExpired = errors.New("launcher access token expired")
	ErrInvalidAuthStateOrCode            = errors.New("invalid auth state or code")
	ErrInvaliClientID                    = errors.New("invalid client id")
	ErrOIDCSessionExpired                = errors.New("session access token expired")
	ErrNoGameManagementRoleUpdated       = errors.New("no game management role updated")
	ErrInvalidRole                       = errors.New("invalid role")
	ErrInvalidGameID                     = errors.New("invalid game id")
	ErrInvalidGameImageID                = errors.New("invalid game image id")
	ErrInvalidUserID                     = errors.New("invalid user id")
	ErrForbidden                         = errors.New("forbidden")
	ErrInvalidFormat                     = errors.New("invalid format")
	ErrNoGame                            = errors.New("no game")
	ErrNoGameImage                       = errors.New("no game image")
	ErrNoGameVideo                       = errors.New("no game video")
	ErrNoGameVersion                     = errors.New("no game version")
	ErrNoGameFile                        = errors.New("no game file")
	ErrNoGameURL                         = errors.New("no game url")
	ErrNoLauncherVersion                 = errors.New("no launcher version")
	ErrGameFileAlreadyExists             = errors.New("game file already exists")
	ErrGameURLAlreadyExists              = errors.New("game url already exists")
	ErrDuplicateGame                     = errors.New("duplicate game")
)
