services:
  collection-server:
    extends:
      file: ../base/compose.yaml
      service: collection-server
    build:
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    volumes:
      - ./.air.toml:/etc/trap-collection/.air.toml
      - ../../:/go/src/github.com/traPtitech/trap-collection-server/
    environment:
      COLLECTION_ENV: development
      STORAGE: local
      ADMINISTRATORS: mazrean,temma,JichouP,wasabi,anko
      FILE_PATH: ./cache
      CLIENT_ID:
      CLIENT_SECRET:
      SESSION_SECRET: secret
      PORT: :3000
    command:
      - -c
      - /etc/trap-collection/.air.toml
    ports: 
      - 3000:3000
  mariadb:
    extends:
      file: ../base/compose.yaml
      service: mariadb
    volumes:
      - ../../mysql/data:/var/lib/mysql
