services:
  collection-proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
      - 8080:80
  collection-server:
    extends:
      file: ../base/compose.yaml
      service: collection-server
    build:
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    volumes:
      - ./.air.toml:/etc/trap-collection/.air.toml
      - ../../:/go/src/github.com/traPtitech/trap-collection-server/
    environment:
      COLLECTION_ENV: development
      STORAGE: local
      ADMINISTRATORS: mazrean,temma,JichouP,wasabi,anko
      FILE_PATH: ./cache
      CLIENT_ID:
      CLIENT_SECRET:
      SESSION_SECRET: secret
    command:
      - -c
      - /etc/trap-collection/.air.toml
    ports:
      - 3000:3000
  mariadb:
    extends:
      file: ../base/compose.yaml
      service: mariadb
    ports:
      - 3306:3306
    volumes:
      - trap_collection_mysql_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8081:8080

volumes:
  trap_collection_mysql_data:
