version: "3"
services:
  collection-server:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    volumes:
      - ../../model/:/go/src/github.com/traPtitech/trap-collection-server/model
      - ../../router/:/go/src/github.com/traPtitech/trap-collection-server/router
      - ../../storage/:/go/src/github.com/traPtitech/trap-collection-server/storage
      - ../../upload/:/go/src/github.com/traPtitech/trap-collection-server/upload
      - ../../session/:/go/src/github.com/traPtitech/trap-collection-server/session
      - ../../main.go:/go/src/github.com/traPtitech/trap-collection-server/main.go
    environment:
      COLLECTION_ENV: development
      OS_AUTH_URL: https://identity.tyo2.conoha.io/v2.0
      OS_USERNAME:
      OS_PASSWORD:
      OS_TENANT_ID:
      CLIENT_ID:
      CLIENT_SECRET:
      PRODUCT_KEY:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: trap_collection
      PORT: :3000
    ports: 
      - 3000:3000
  mariadb:
    image: mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ../../mysql/data:/var/lib/mysql
      - ../../mysql/init:/docker-entrypoint-initdb.d