services:
  collection-server:
    build:
      context: ../..
    environment:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: trap_collection
      S3_ACCESS_KEY_ID: AKID
      S3_SECRET_ACCESS_KEY: SECRETPASSWORD
      S3_REGION: us-east-1
      S3_BUCKET: trap-collection
      S3_ENDPOINT: http://s3:9000
      S3_USE_PATH_STYLE: false
      PORT: :3000
      MIGRATION_EMPTY_DB: true
      # MIGRATION_BASELINE: "20250327121655" DBが空じゃないときのbaseline。基本的にコメントアウトしたままでよい
    healthcheck:
      test:
        ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/api/metrics"]
      timeout: 5m
      interval: 1s
      retries: 1000

  mariadb:
    image: mariadb:13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: trap_collection
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ppass"]
      timeout: 5m
      interval: 1s
      retries: 1000

  s3:
    image: rustfs/rustfs:1.0.0-rc.6@sha256:97171b3d72cd47dc81000f92ea84de25608bfc35a94c965501afaeb5d99f6035
    # 9000-API, 9001-Web
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY: AKID
      RUSTFS_SECRET_KEY: SECRETPASSWORD
      RUSTFS_SERVER_DOMAINS: s3
      RUSTFS_REGION: us-east-1
      RUSTFS_VOLUMES: /data
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/ready"]
      timeout: 5m
      interval: 1s
      retries: 1000
    networks:
      default:
        aliases:
          - trap-collection.s3
