services:
  collection-server:
    build:
      context: ../..
    environment:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: trap_collection
      S3_ACCESS_KEY_ID: AKID
      S3_SECRET_ACCESS_KEY: SECRETPASSWORD
      S3_REGION: us-east-1
      S3_BUCKET: trap-collection
      S3_ENDPOINT: http://s3:9000
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:10.6.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: trap_collection
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-ppass"]
      timeout: 5m
      interval: 1s
      retries: 1000

  s3:
    image: minio/minio:RELEASE.2022-09-17T00-09-45Z
    # 9000-API, 9001-Web
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: AKID
      MINIO_ROOT_PASSWORD: SECRETPASSWORD
      MINIO_DOMAIN: s3
      MINIO_SITE_REGION: us-east-1
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck.sh"]
      timeout: 5m
      interval: 1s
      retries: 1000
