FROM node:lts-alpine AS build
WORKDIR /app
RUN apk add --no-cache git && \
  apk --update add tzdata && \
  cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
  apk del tzdata && \
  rm -rf /var/cache/apk/*

COPY ./package*.json ./
RUN yarn install
COPY . .
RUN npm run build

FROM abiosoft/caddy:0.11.5-no-stats
EXPOSE 8080
COPY Caddyfile /etc/Caddyfile
COPY --from=build /app/build /srv