version: "2"
issues:
  max-same-issues: 0
linters:
  enable:
    - revive
  settings:
    staticcheck:
      checks:
        - -SA3000
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - openapi
      - mock
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - openapi
      - mock
      - third_party$
      - builtin$
      - examples$
