version: "3"
services:
  server:
    build: ./
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "pass"
      DB_HOSTNAME: mysql
      DB_PORT: "3306"
      DB_DATABASE: "trap_collection"
      PORT: ":3000"
      OS_AUTH_URL:
      OS_USERNAME:
      OS_PASSWORD:
      OS_TENANT_ID:
    links:
      - mysql
    ports:
      - "3000:3000"
    restart: always
  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"