version: "3"
services:
  server:
    build: ./
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "pass"
      DB_HOSTNAME: mysql
      DB_PORT: "3306"
      DB_DATABASE: "trap-collection"
      PORT: ":3000"
    links:
      - mysql
    ports:
      - "3000:3000"
    restart: always
  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "trap-collection"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"