version: '3'

includes:
  os:
    taskfile: ./task/Taskfile_{{OS}}.yml
    internal: true

tasks:
  default:
    cmds:
      - task: download
      - task: generate

  download:
    cmds:
      - task: os:download

  wire:
    cmds:
      - task: os:wire

  openapi:
    cmds:
      - task: os:openapi

  generate:
    cmds:
      - task: os:generate

  dev:
    cmds:
      - task: dev:v2

  dev:v2:
    cmds:
      - task: os:dev:v2
    deps:
      - wire
      - openapi

  dev:v1:
    cmds:
      - task: os:dev:v1
    deps:
      - wire
      - openapi

  dev:down:
    cmds:
      - task: os:dev:down

  test:
    cmds:
      - task: os:test
    deps:
      - generate

  tbls:
    cmds:
      - task: os:tbls
    deps:
      - wire
      - openapi

  tbls:down:
    cmds:
      - task: os:tbls:down

  down:
    cmds:
      - task: dev:down
      - task: tbls:down

  clean:db:
    cmds:
      - task: os:clean:db
