version: "3"
services:
  collection-nginx:
    image: nginx:1.17.10
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  collection-mock:
    build:
      context: ../../mock
      dockerfile: ./Dockerfile
    restart: always
  collection-staging:
    build:
      context: ../../
      dockerfile: ./docker/mock/Dockerfile
    restart: always
    environment:
      COLLECTION_ENV: mock
      OS_AUTH_URL: https://identity.tyo2.conoha.io/v2.0
      OS_USERNAME:
      OS_PASSWORD:
      OS_TENANT_ID:
      CLIENT_ID:
      CLIENT_SECRET:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: collection-mariadb
      DB_PORT: 3306
      DB_DATABASE: trap_collection
      PORT: :3000
  collection-mariadb:
    image: mariadb:10.5.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ../../mysql/init:/docker-entrypoint-initdb.d
      - ../../mysql/data/mock:/var/lib/mysql