services:
  mariadb:
    image: mariadb:12.3.2@sha256:a02fe89cb597d4375812b2eac90cf9d0775d4686daa7f7cc750ebbcad7525bbc
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: trap_collection
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ppass"]
      timeout: 5s
      interval: 10s
      retries: 10

  atlas:
    image: arigaio/atlas:latest
    command: ["migrate", "apply", "--config", "file://atlas.ci.hcl", "--env", "docker"]
    volumes:
      - ../../:/work
    working_dir: /work
    depends_on:
      mariadb:
        condition: service_healthy
  tbls:
    image: k1low/tbls:v1.96.0
    environment:
      TBLS_DSN: mariadb://root:pass@mariadb:3306/trap_collection
    volumes:
      - ../../:/work
    working_dir: /work
    command: doc --rm-dist -c .tbls.yml
    depends_on:
      mariadb:
        condition: service_healthy
      atlas:
        condition: service_completed_successfully
