services:
  mariadb:
    image: mariadb:10.6.4@sha256:c014ba1efc5dbd711d0520c7762d57807f35549de3414eb31e942a420c8a2ed2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: trap_collection
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ppass"]
      timeout: 5s
      interval: 10s
      retries: 10

  atlas:
    image: arigaio/atlas:latest
    command: ["migrate", "apply", "--config", "file://atlas.ci.hcl", "--env", "ci"]
    volumes:
      - ../../:/work
    working_dir: /work
    depends_on:
      mariadb:
        condition: service_healthy
  tbls:
    image: k1low/tbls:v1.94.5
    environment:
      TBLS_DSN: mariadb://root:pass@mariadb:3306/trap_collection
    volumes:
      - ../../:/work
    working_dir: /work
    command: doc --rm-dist
    depends_on:
      mariadb:
        condition: service_healthy
      atlas:
        condition: service_completed_successfully
