-- Modify "v2_game_versions" table
ALTER TABLE `v2_game_versions` ADD CONSTRAINT `fk_games_game_versions_v2` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- Modify "edition_game_version_relations" table
ALTER TABLE `edition_game_version_relations` RENAME INDEX `fk_edition_game_version_relations_game_version_table2_v2` TO `fk_edition_game_version_relations_game_version_table2`, DROP FOREIGN KEY `fk_edition_game_version_relations_edition_table_v2`, DROP FOREIGN KEY `fk_edition_game_version_relations_game_version_table2_v2`, ADD CONSTRAINT `fk_edition_game_version_relations_edition_table` FOREIGN KEY (`edition_id`) REFERENCES `editions` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT, ADD CONSTRAINT `fk_edition_game_version_relations_game_version_table2` FOREIGN KEY (`game_version_id`) REFERENCES `v2_game_versions` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- Modify "game_genre_relations" table
ALTER TABLE `game_genre_relations` DROP PRIMARY KEY, ADD PRIMARY KEY (`game_id`, `genre_id`), DROP INDEX `fk_game_genre_relations_game_table2_v13`, ADD INDEX `fk_game_genre_relations_game_genre_table` (`genre_id`), DROP FOREIGN KEY `fk_game_genre_relations_game_genre_table_v10`, DROP FOREIGN KEY `fk_game_genre_relations_game_genre_table_v11`, DROP FOREIGN KEY `fk_game_genre_relations_game_genre_table_v12`, DROP FOREIGN KEY `fk_game_genre_relations_game_genre_table_v13`, DROP FOREIGN KEY `fk_game_genre_relations_game_table2_v11`, DROP FOREIGN KEY `fk_game_genre_relations_game_table2_v12`, DROP FOREIGN KEY `fk_game_genre_relations_game_table2_v13`, DROP FOREIGN KEY `fk_game_genre_relations_game_table2_v5`, ADD CONSTRAINT `fk_game_genre_relations_game_genre_table` FOREIGN KEY (`genre_id`) REFERENCES `game_genres` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT, ADD CONSTRAINT `fk_game_genre_relations_game_table2` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- Modify "game_version_game_file_relations" table
ALTER TABLE `game_version_game_file_relations` RENAME INDEX `fk_game_version_game_file_relations_game_file_table2_v5` TO `fk_game_version_game_file_relations_game_file_table2`, DROP FOREIGN KEY `fk_game_version_game_file_relations_game_file_table2_v2`, DROP FOREIGN KEY `fk_game_version_game_file_relations_game_file_table2_v5`, DROP FOREIGN KEY `fk_game_version_game_file_relations_game_version_table2_v15`, DROP FOREIGN KEY `fk_game_version_game_file_relations_game_version_table2_v2`, DROP FOREIGN KEY `fk_game_version_game_file_relations_game_version_table2_v4`, ADD CONSTRAINT `fk_game_version_game_file_relations_game_file_table2` FOREIGN KEY (`game_file_id`) REFERENCES `v2_game_files` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT, ADD CONSTRAINT `fk_game_version_game_file_relations_game_version_table2` FOREIGN KEY (`game_version_id`) REFERENCES `v2_game_versions` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- Modify "game_versions" table
ALTER TABLE `game_versions` RENAME INDEX `fk_games_game_versions` TO `fk_games_game_versions_v1`, DROP FOREIGN KEY `fk_games_game_versions`, ADD CONSTRAINT `fk_games_game_versions_v1` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- Modify "launcher_version_game_relations" table
ALTER TABLE `launcher_version_game_relations` RENAME INDEX `fk_launcher_version_game_relations_game_table` TO `fk_launcher_version_game_relations_game_table2`, DROP FOREIGN KEY `fk_launcher_version_game_relations_game_table`, ADD CONSTRAINT `fk_launcher_version_game_relations_game_table2` FOREIGN KEY (`game_table_id`) REFERENCES `games` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
