name: Task
description: 新機能やバグ修正とは異なる、コーディングを伴わないタスクのための Issue。
labels:
  - task
body:
  - type: textarea
    id: description
    attributes:
      label: 説明
      description: タスクの内容を詳しく書いてください
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 注意点
      description: タスクにあたっての注意点や、特に考慮すべき点があれば書いてください
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: その他
      description: その他
    validations:
      required: false
