/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Game - ゲーム
type Game struct {

	// ゲームのUUID
	Id string `json:"id"`

	// ゲーム名
	Name string `json:"name"`

	// ゲームの説明
	Description string `json:"description,omitempty"`

	// ゲームの登録時刻
	CreatedAt time.Time `json:"createdAt"`

	Version *GameVersion `json:"version,omitempty"`
}
