/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Maintainer struct {

	// traQID（UUID）
	Id string `json:"id"`

	// traQID（UUIDでない方）
	Name string `json:"name"`

	// 権限（0:ゲームの更新の権限のみ,1:ゲームの更新と更新権限を持つ人の追加の権限を持つ）
	Role int32 `json:"role"`
}
