/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GameIDs - ゲームのUUIDの一覧
type GameIDs struct {

	// ゲームのUUIDの配列
	GameIDs []string `json:"gameIDs,omitempty"`
}
