/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Maintainers - 管理者の一覧
type Maintainers struct {

	Maintainers []string `json:"maintainers"`
}
