/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Seat - 席
type Seat struct {

	SeatVersionId int32 `json:"seatVersionId"`

	SeatId int32 `json:"seatId"`
}
