/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NewVersion - 新しいランチャーのバージョンの名前
type NewVersion struct {

	// バージョンの名前
	Name string `json:"name"`

	// アンケートのURL
	AnkeTo string `json:"anke-to,omitempty"`
}
