/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// SeatVersion - 席のバージョン
type SeatVersion struct {

	Id string `json:"id"`

	Width int32 `json:"width"`

	Hight int32 `json:"hight,omitempty"`

	// 作成時刻
	CreatedAt time.Time `json:"createdAt"`
}
