/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NewSeatVersion - 新しい席のバージョン
type NewSeatVersion struct {
	Width int32 `json:"width"`

	Hight int32 `json:"hight,omitempty"`
}
