/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// User - ユーザー
type User struct {

	// traQのID（UUID）
	Id string `json:"id,omitempty"`

	// traQID（UUIDでない方）
	Name string `json:"name"`
}
