/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProductKeyGen - プロダクトキー生成のリクエスト
type ProductKeyGen struct {
	Num int32 `json:"num"`

	// バージョンID
	Version string `json:"version"`
}
