/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// SeatDetail - 席の詳細
type SeatDetail struct {
	Id int32 `json:"id"`

	// 席の状態(0で離席、1で着席)
	Status int32 `json:"status"`

	// 着席時刻
	SeatingTime *time.Time `json:"seatingTime,omitempty"`
}
