/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// VersionDetails - ランチャーのバージョン詳細
type VersionDetails struct {

	// ID
	Id string `json:"id"`

	// 名前
	Name string `json:"name"`

	// アンケートのURL
	AnkeTo string `json:"anke-to,omitempty"`

	Games []GameMeta `json:"games"`

	// 登録時刻
	CreatedAt time.Time `json:"createdAt"`
}
