/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GameMeta - ゲーム名とID
type GameMeta struct {

	// 追加されたゲームのUUID
	Id string `json:"id"`

	// 追加されたゲームの名前
	Name string `json:"name"`
}
