/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProductKeyDetail - プロダクトキーの詳細
type ProductKeyDetail struct {

	// プロダクトキーのID
	Id string `json:"id,omitempty"`

	// プロダクトキー
	Key string `json:"key"`
}
