/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProductKey - プロダクトキー
type ProductKey struct {

	// プロダクトキー
	Key string `json:"key"`
}
