/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NewGameFile - 新しいゲームのファイル
type NewGameFile struct {

	// ゲームの種類（jar,windows,mac）
	FileType string `json:"fileType"`

	// ゲームの起動時に実行するファイル
	EntryPoint string `json:"entryPoint"`

	// ゲームのファイル
	File *ioReadCloser `json:"file"`
}
