/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LauncherAuthToken - ランチャーのトークン
type LauncherAuthToken struct {

	AccessToken string `json:"accessToken"`

	// アクセストークンの持続時間(秒)
	ExpiresIn int32 `json:"expiresIn"`

	RefreshToken string `json:"refreshToken"`
}
