/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GameUrl - ゲームのURLの情報
type GameUrl struct {

	// アセットのID
	Id string `json:"id"`

	// ゲームのURL（タイプがURL以外のときはなし）
	Url string `json:"url"`
}
