/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NewGameUrl - 新しいゲームのURL
type NewGameUrl struct {

	// URL
	Url string `json:"url"`
}
