/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NewGameVersion - 新しいゲームのバージョン
type NewGameVersion struct {

	// 名前
	Name string `json:"name"`

	// バージョンの説明
	Description string `json:"description"`
}
