/*
 * traPCollection API
 *
 * traPCollectionのAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	echo "github.com/labstack/echo/v4"
)

func SetupRouting(e *echo.Echo, api *Api) {

	e.DELETE("/api/games/:gameID", DeleteGamesHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.GET("/api/games/:gameID/info", GetGameHandler(api.GameApi), api.BothAuthMiddleware)
	e.GET("/api/games/asset/:gameID/file", GetGameFileHandler(api.GameApi), api.BothAuthMiddleware)
	e.GET("/api/games/asset/:gameID/url", GetGameURLHandler(api.GameApi), api.BothAuthMiddleware)
	e.GET("/api/games/:gameID/version", GetGameVersionHandler(api.GameApi), api.TrapMemberAuthMiddleware)
	e.GET("/api/games", GetGamesHandler(api.GameApi), api.TrapMemberAuthMiddleware)
	e.GET("/api/games/:gameID/image", GetImageHandler(api.GameApi), api.BothAuthMiddleware)
	e.GET("/api/games/:gameID/maintainers", GetMaintainerHandler(api.GameApi), api.TrapMemberAuthMiddleware)
	e.GET("/api/games/:gameID/video", GetVideoHandler(api.GameApi), api.BothAuthMiddleware)
	e.POST("/api/games/asset/:gameID/file", PostFileHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.POST("/api/games", PostGameHandler(api.GameApi), api.TrapMemberAuthMiddleware)
	e.POST("/api/games/:gameID/version", PostGameVersionHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.POST("/api/games/:gameID/image", PostImageHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.POST("/api/games/:gameID/maintainers", PostMaintainerHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameOwnerAuthMiddleware)
	e.POST("/api/games/asset/:gameID/url", PostURLHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.POST("/api/games/:gameID/video", PostVideoHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.PUT("/api/games/:gameID/info", PutGameHandler(api.GameApi), api.TrapMemberAuthMiddleware, api.GameMaintainerAuthMiddleware)
	e.DELETE("/api/launcher/key/:productKeyID", DeleteProductKeyHandler(api.LauncherAuthApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
	e.GET("/api/launcher/me", GetLauncherMeHandler(api.LauncherAuthApi), api.LauncherAuthMiddleware)
	e.GET("/api/versions/:launcherVersionID/keys", GetProductKeysHandler(api.LauncherAuthApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
	e.POST("/api/launcher/key/generate", PostKeyGenerateHandler(api.LauncherAuthApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
	e.POST("/api/launcher/login", PostLauncherLoginHandler(api.LauncherAuthApi))
	e.GET("/api/oauth2/callback", CallbackHandler(api.Oauth2Api))
	e.GET("/api/oauth2/generate/code", GetGeneratedCodeHandler(api.Oauth2Api))
	e.POST("/api/oauth2/logout", PostLogoutHandler(api.Oauth2Api), api.TrapMemberAuthMiddleware)
	e.DELETE("/api/seats", DeleteSeatHandler(api.SeatApi), api.LauncherAuthMiddleware)
	e.GET("/api/seats/versions/:seatVersionID", GetSeatsHandler(api.SeatApi), api.TrapMemberAuthMiddleware)
	e.POST("/api/seats", PostSeatHandler(api.SeatApi), api.LauncherAuthMiddleware)
	e.DELETE("/api/seats/versions/:seatVersionID", DeleteSeatVersionHandler(api.SeatVersionApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
	e.POST("/api/seats/versions", PostSeatVersionHandler(api.SeatVersionApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
	e.GET("/api/users/me", GetMeHandler(api.UserApi), api.TrapMemberAuthMiddleware)
	e.GET("/api/users", GetUsersHandler(api.UserApi), api.TrapMemberAuthMiddleware)
	e.GET("/api/versions/check", GetCheckListHandler(api.VersionApi), api.LauncherAuthMiddleware)
	e.GET("/api/versions/:launcherVersionID", GetVersionHandler(api.VersionApi), api.BothAuthMiddleware)
	e.GET("/api/versions", GetVersionsHandler(api.VersionApi), api.TrapMemberAuthMiddleware)
	e.POST("/api/versions/:launcherVersionID/game", PostGameToVersionHandler(api.VersionApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
	e.POST("/api/versions", PostVersionHandler(api.VersionApi), api.TrapMemberAuthMiddleware, api.AdminAuthMiddleware)
}
