FROM golang:1.14.0-alpine AS build
WORKDIR /go/src
RUN apk add --update --no-cache git && \
	apk --update add tzdata && \
	cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
	apk del tzdata && \
	rm -rf /var/cache/apk/*
COPY {{apiPath}} ./
RUN go mod download
RUN go build -o {{packageName}}

FROM scratch AS runtime
COPY --from=build /go/src/{{packageName}} ./
EXPOSE 8080/tcp
ENTRYPOINT ./{{packageName}}
