name: PR Agent
on:
  pull_request:
    types:
      - ready_for_review
      - opened
  issue_comment:
    types:
      - created
      - edited

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  pr_agent_job:
    if: ${{github.event.sender.type != 'Bot' && github.event.pull_request.draft == false}}
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@v0.24
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION.AUTO_REVIEW: "true"
          GITHUB_ACTION.AUTO_DESCRIBE: "true"
          GITHUB_ACTION.AUTO_IMPROVE: "true"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "必ず日本語で回答してください"
          PR_DESCRIPTION.PUBLISH_LABELS: "false"
          PR_DESCRIPTION.ADD_ORIGINAL_USER_DESCRIPTION: "true"
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Please use Japanese in descriptions."
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "Please use Japanese in descriptions."
          IGNORE.GLOB: "['*.gen.go']"
